version: '0.1'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/data
      - ./InitDb/backup.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - web

  my_web:
    image: 'dvgs:latest'
    build:
      context: ./GiaSuService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__TutorConnection=User ID=${POSTGRES_USER};Server=postgres;Port=5432;Database=${POSTGRES_DB};Password=${POSTGRES_PASSWORD};Pooling=True;
    networks:
      - web
    depends_on:
      - postgres

networks:
  web:
  
volumes:
  app-data: